### ISSUE TITLE
The Performance on Cityscapes or BSD?

### ISSUE THREAD

**Issue by FengLoveBella** [lijiaman/CASENet#1]
@lijiaman Great job!!! What's the performance of your CASENet code on Cityscapes or SBD? Can you share the experimental result or the train model? Tks very much!

**Comment by lijiaman** [comment]
Hi, this is the code for SBD dataset. I kind of rushed through this project
for course ;),  didn't reproduce the results. (I think there maybe some
bugs..sorry..) Maybe will fix them later when I get time. Thanks.

**Comment by FengLoveBella** [comment]
@lijiaman Thanks a lot.

**Comment by FengLoveBella** [comment]
@lijiaman Could you share your train_aug_label_binary_np.h5 and test_label_binary_np.h5? I found to run your code, these two files are not exist in your repo. Thank you very much.

**Comment by lijiaman** [comment]
sorry, data have been deleted... I'd suggest to download the dataset and
generate jpg to store instead of other format. (just need to change a
little bit in data loader).
